### ISSUE TITLE
Code Availability !

### ISSUE THREAD

**Issue by MuhammadNawazkhan** [MinkaiXu/SobolevWassersteinGAN#1]
Hi Dear, I'm following your work and waiting for Code availability. Please upload the code or update me when it will be available?
This will help me a lot in my research work. I'll be happy to get the code ASAP. Thank you.

**Comment by MinkaiXu** [comment]
Hi Dear!

Sorry for the late reply. 
Kind of busy recently with the ICML deadline, the new semester, and so on. 
Code is available now!

Thanks
Minkai
